spring:
  profiles:
    active: dev
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  application:
    name: taibiex-staking-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    open-in-view: false

    properties:
      hibernate:
        format_sql: true # 以便以更易读的格式打印 SQL
        use_sql_comments: true


logging:
  level:
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: debug
            StatementCreatorUtils: trace

      hibernate:
        SQL: debug # logging.level.org.hibernate.SQL: 将日志级别设置为 DEBUG，以便打印 SQL 语句
        type:
          descriptor:
            sql:
              BasicBinder: trace  # 将日志级别设置为 TRACE，以打印参数绑定的详细信息
        orm:
          jdbc:
            bind: trace # https://blog.csdn.net/zhaolinfenggg/article/details/135706459

    root: info # debug


# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.taibiex.stakingservice.controller

app:
  total-reward-amount: 100000000000000000000